//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from lisp_gammar.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class lisp_gammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, LB=16, RB=17, 
		IF=18, BOOL_VAL=19, NUMBER=20, ID=21, WS=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "LB", "RB", "IF", 
		"BOOL_VAL", "NUMBER", "ID", "WS"
	};


	public lisp_gammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public lisp_gammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'print-num'", "'print-bool'", "'+'", "'-'", "'*'", "'/'", "'mod'", 
		"'>'", "'<'", "'='", "'and'", "'or'", "'not'", "'define'", "'fun'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, "LB", "RB", "IF", "BOOL_VAL", "NUMBER", "ID", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "lisp_gammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static lisp_gammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\x99', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', 'x', 
		'\n', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', 
		'}', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\x80', '\v', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\x85', '\n', 
		'\x15', '\f', '\x15', '\xE', '\x15', '\x88', '\v', '\x15', '\x5', '\x15', 
		'\x8A', '\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\x8E', 
		'\n', '\x16', '\f', '\x16', '\xE', '\x16', '\x91', '\v', '\x16', '\x3', 
		'\x17', '\x6', '\x17', '\x94', '\n', '\x17', '\r', '\x17', '\xE', '\x17', 
		'\x95', '\x3', '\x17', '\x3', '\x17', '\x2', '\x2', '\x18', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'\x3', '\x2', '\t', '\x3', '\x2', '\x32', '\x32', '\x3', '\x2', '\x33', 
		';', '\x3', '\x2', '\x32', ';', '\x3', '\x2', '/', '/', '\x3', '\x2', 
		'\x63', '|', '\x5', '\x2', '/', '/', '\x32', ';', '\x63', '|', '\x5', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x9F', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '/', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\a', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\x46', '\x3', '\x2', '\x2', '\x2', '\v', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'J', '\x3', '\x2', '\x2', '\x2', '\xF', 'L', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'P', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'R', '\x3', '\x2', '\x2', '\x2', '\x15', 'T', '\x3', '\x2', '\x2', '\x2', 
		'\x17', 'V', '\x3', '\x2', '\x2', '\x2', '\x19', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', ']', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x61', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', 'h', '\x3', '\x2', '\x2', '\x2', '!', 'l', 
		'\x3', '\x2', '\x2', '\x2', '#', 'n', '\x3', '\x2', '\x2', '\x2', '%', 
		'p', '\x3', '\x2', '\x2', '\x2', '\'', 'w', '\x3', '\x2', '\x2', '\x2', 
		')', '\x89', '\x3', '\x2', '\x2', '\x2', '+', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '-', '\x93', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\a', 'r', 
		'\x2', '\x2', '\x30', '\x31', '\a', 't', '\x2', '\x2', '\x31', '\x32', 
		'\a', 'k', '\x2', '\x2', '\x32', '\x33', '\a', 'p', '\x2', '\x2', '\x33', 
		'\x34', '\a', 'v', '\x2', '\x2', '\x34', '\x35', '\a', '/', '\x2', '\x2', 
		'\x35', '\x36', '\a', 'p', '\x2', '\x2', '\x36', '\x37', '\a', 'w', '\x2', 
		'\x2', '\x37', '\x38', '\a', 'o', '\x2', '\x2', '\x38', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '\x39', ':', '\a', 'r', '\x2', '\x2', ':', ';', '\a', 
		't', '\x2', '\x2', ';', '<', '\a', 'k', '\x2', '\x2', '<', '=', '\a', 
		'p', '\x2', '\x2', '=', '>', '\a', 'v', '\x2', '\x2', '>', '?', '\a', 
		'/', '\x2', '\x2', '?', '@', '\a', '\x64', '\x2', '\x2', '@', '\x41', 
		'\a', 'q', '\x2', '\x2', '\x41', '\x42', '\a', 'q', '\x2', '\x2', '\x42', 
		'\x43', '\a', 'n', '\x2', '\x2', '\x43', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\x45', '\a', '-', '\x2', '\x2', '\x45', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'G', '\a', '/', '\x2', '\x2', 'G', '\n', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'I', '\a', ',', '\x2', '\x2', 'I', '\f', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'K', '\a', '\x31', '\x2', '\x2', 'K', '\xE', '\x3', 
		'\x2', '\x2', '\x2', 'L', 'M', '\a', 'o', '\x2', '\x2', 'M', 'N', '\a', 
		'q', '\x2', '\x2', 'N', 'O', '\a', '\x66', '\x2', '\x2', 'O', '\x10', 
		'\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\a', '@', '\x2', '\x2', 'Q', '\x12', 
		'\x3', '\x2', '\x2', '\x2', 'R', 'S', '\a', '>', '\x2', '\x2', 'S', '\x14', 
		'\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', '?', '\x2', '\x2', 'U', '\x16', 
		'\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', '\x63', '\x2', '\x2', 'W', 
		'X', '\a', 'p', '\x2', '\x2', 'X', 'Y', '\a', '\x66', '\x2', '\x2', 'Y', 
		'\x18', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', 'q', '\x2', '\x2', 
		'[', '\\', '\a', 't', '\x2', '\x2', '\\', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', ']', '^', '\a', 'p', '\x2', '\x2', '^', '_', '\a', 'q', '\x2', 
		'\x2', '_', '`', '\a', 'v', '\x2', '\x2', '`', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x62', '\a', '\x66', '\x2', '\x2', '\x62', '\x63', '\a', 
		'g', '\x2', '\x2', '\x63', '\x64', '\a', 'h', '\x2', '\x2', '\x64', '\x65', 
		'\a', 'k', '\x2', '\x2', '\x65', '\x66', '\a', 'p', '\x2', '\x2', '\x66', 
		'g', '\a', 'g', '\x2', '\x2', 'g', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'h', 'i', '\a', 'h', '\x2', '\x2', 'i', 'j', '\a', 'w', '\x2', '\x2', 
		'j', 'k', '\a', 'p', '\x2', '\x2', 'k', ' ', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\a', '*', '\x2', '\x2', 'm', '\"', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\a', '+', '\x2', '\x2', 'o', '$', '\x3', '\x2', '\x2', '\x2', 
		'p', 'q', '\a', 'k', '\x2', '\x2', 'q', 'r', '\a', 'h', '\x2', '\x2', 
		'r', '&', '\x3', '\x2', '\x2', '\x2', 's', 't', '\a', '%', '\x2', '\x2', 
		't', 'x', '\a', 'h', '\x2', '\x2', 'u', 'v', '\a', '%', '\x2', '\x2', 
		'v', 'x', '\a', 'v', '\x2', '\x2', 'w', 's', '\x3', '\x2', '\x2', '\x2', 
		'w', 'u', '\x3', '\x2', '\x2', '\x2', 'x', '(', '\x3', '\x2', '\x2', '\x2', 
		'y', '\x8A', '\t', '\x2', '\x2', '\x2', 'z', '~', '\t', '\x3', '\x2', 
		'\x2', '{', '}', '\t', '\x4', '\x2', '\x2', '|', '{', '\x3', '\x2', '\x2', 
		'\x2', '}', '\x80', '\x3', '\x2', '\x2', '\x2', '~', '|', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x8A', 
		'\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\t', '\x5', '\x2', '\x2', '\x82', '\x86', '\t', '\x3', '\x2', 
		'\x2', '\x83', '\x85', '\t', '\x4', '\x2', '\x2', '\x84', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x88', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x88', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x89', 'y', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'z', '\x3', '\x2', '\x2', '\x2', '\x89', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '*', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8F', '\t', 
		'\x6', '\x2', '\x2', '\x8C', '\x8E', '\t', '\a', '\x2', '\x2', '\x8D', 
		'\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x90', ',', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x92', '\x94', '\t', '\b', '\x2', 
		'\x2', '\x93', '\x92', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x93', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x97', '\x98', '\b', '\x17', '\x2', '\x2', '\x98', '.', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\x2', 'w', '~', '\x86', '\x89', '\x8F', '\x95', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
